# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Align_helper.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(1022, 790)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.dockWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1011, 761))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(1)
        self.gridLayout.setVerticalSpacing(11)
        self.gridLayout.setObjectName("gridLayout")
        self.centroidX = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.centroidX.setObjectName("centroidX")
        self.gridLayout.addWidget(self.centroidX, 0, 0, 1, 1)
        self.CentroidY = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.CentroidY.setObjectName("CentroidY")
        self.gridLayout.addWidget(self.CentroidY, 0, 1, 1, 1)
        self.slopes = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.slopes.setObjectName("slopes")
        self.gridLayout.addWidget(self.slopes, 1, 0, 1, 1)
        self.heights = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.heights.setObjectName("heights")
        self.gridLayout.addWidget(self.heights, 1, 1, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DockWidget = QtWidgets.QDockWidget()
    ui = Ui_DockWidget()
    ui.setupUi(DockWidget)
    DockWidget.show()
    sys.exit(app.exec_())
