# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laser_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget, QPushButton, QLineEdit, QLabel, QHBoxLayout
from Graphics.BaseClasses import MyLabel, MyPushButton, MyTextBrowser


class Ui_LaserController(object):
    def setupUi(self, LaserController):
        LaserController.setObjectName("LaserController")
        LaserController.resize(415, 236)
        LaserController.setWindowTitle("Obis Laser Controller")
        LaserController.setToolTip("")
        LaserController.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(LaserController)
        layout = QVBoxLayout(LaserController)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(180, 10, 211, 151))
        self.widget.setObjectName("widget")


        self.indicators = MyLabel(self.widget)
        self.indicators.setGeometry(QtCore.QRect(50, 10, 121, 20))
        self.indicators.setObjectName("indicators")
        layout.addWidget(self.indicators)

        self.comms_label = MyLabel(self.widget)
        self.comms_label.setGeometry(QtCore.QRect(0, 30, 61, 20))
        self.comms_label.setObjectName("comms_label")
        layout.addWidget(self.comms_label)

        self.comms_onoff = MyLabel(self.widget)
        self.comms_onoff.setGeometry(QtCore.QRect(150, 30, 31, 21))
        self.comms_onoff.setText("")
        self.comms_onoff.setObjectName("comms_onoff")
        layout.addWidget(self.comms_onoff)

        self.laser_label = MyLabel(self.widget)
        self.laser_label.setGeometry(QtCore.QRect(0, 50, 61, 20))
        self.laser_label.setObjectName("laser_label")
        layout.addWidget(self.laser_label)

        self.laser_onoff = MyLabel(self.widget)
        self.laser_onoff.setGeometry(QtCore.QRect(130, 50, 31, 21))
        self.laser_onoff.setText("")
        self.laser_onoff.setObjectName("laser_onoff")
        layout.addWidget(self.laser_onoff)

        self.wavelength_label = MyLabel(self.widget)
        self.wavelength_label.setGeometry(QtCore.QRect(0, 70, 111, 20))
        self.wavelength_label.setObjectName("wavelength_label")


        self.wlength_display = MyTextBrowser(self.widget)
        self.wlength_display.setGeometry(QtCore.QRect(130, 70, 71, 21))
        self.wlength_display.setObjectName("wlength_display")
        self.int_display_2 = MyLabel(self.widget)
        self.int_display_2.setGeometry(QtCore.QRect(0, 90, 111, 20))
        self.int_display_2.setObjectName("int_display_2")
        self.int_display = MyTextBrowser(self.widget)
        self.int_display.setGeometry(QtCore.QRect(130, 90, 71, 21))
        self.int_display.setObjectName("int_display")
        self.cur_label = MyLabel(self.widget)
        self.cur_label.setGeometry(QtCore.QRect(0, 110, 111, 20))
        self.cur_label.setObjectName("cur_label")
        self.cur_display = MyTextBrowser(self.widget)
        self.cur_display.setGeometry(QtCore.QRect(130, 110, 71, 21))
        self.cur_display.setObjectName("cur_display")
        self.pushButton = MyPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 50, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 100, 111, 22))
        self.horizontalSlider.setToolTip("")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        LaserController.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LaserController)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 24))
        self.menubar.setObjectName("menubar")
        LaserController.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LaserController)
        self.statusbar.setObjectName("statusbar")
        LaserController.setStatusBar(self.statusbar)

        self.retranslateUi(LaserController)
        QtCore.QMetaObject.connectSlotsByName(LaserController)

    def retranslateUi(self, LaserController):
        _translate = QtCore.QCoreApplication.translate
        self.indicators.setText(_translate("LaserController", "Status indicators"))
        self.comms_label.setText(_translate("LaserController", "Comms"))
        self.laser_label.setText(_translate("LaserController", "Laser"))
        self.wavelength_label.setText(_translate("LaserController", "Wavelength (nm)"))
        self.int_display_2.setText(_translate("LaserController", "Intensity (W)"))
        self.cur_label.setText(_translate("LaserController", "Current (A)"))
        self.pushButton.setText(_translate("LaserController", "Laser ON/OFF"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LaserController = QtWidgets.QMainWindow()
    ui = Ui_LaserController()
    ui.setupUi(LaserController)
    LaserController.show()
    sys.exit(app.exec_())
