# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laser_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from Graphics.Base_Classes_graphics.BaseClasses import *


class Ui_LaserController(object):
    def setupUi(self, LaserController):
        LaserController.setObjectName("LaserController")
        LaserController.resize(468, 235)
        LaserController.setWindowTitle("Obis Laser Controller")
        LaserController.setToolTip("")
        LaserController.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(LaserController)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(220, 0, 201, 184))
        self.widget.setObjectName("widget")
        self.indicators = MyLabel(self.widget)
        self.indicators.setGeometry(QtCore.QRect(40, 3, 121, 20))
        self.indicators.setObjectName("indicators")
        self.wavelength_label = MyLabel(self.widget)
        self.wavelength_label.setGeometry(QtCore.QRect(0, 120, 111, 20))
        self.wavelength_label.setObjectName("wavelength_label")
        self.wlength_display = MyTextBrowser(self.widget)
        self.wlength_display.setGeometry(QtCore.QRect(130, 120, 71, 21))
        self.wlength_display.setObjectName("wlength_display")
        self.int_display_2 = MyLabel(self.widget)
        self.int_display_2.setGeometry(QtCore.QRect(0, 140, 111, 20))
        self.int_display_2.setObjectName("int_display_2")
        self.int_display = MyTextBrowser(self.widget)
        self.int_display.setGeometry(QtCore.QRect(130, 140, 71, 21))
        self.int_display.setObjectName("int_display")
        self.cur_label = MyLabel(self.widget)
        self.cur_label.setGeometry(QtCore.QRect(0, 160, 111, 20))
        self.cur_label.setObjectName("cur_label")
        self.cur_display = MyTextBrowser(self.widget)
        self.cur_display.setGeometry(QtCore.QRect(130, 160, 71, 21))
        self.cur_display.setObjectName("cur_display")
        self.comms_onoff = MyIndicator(self.widget)
        self.comms_onoff.setGeometry(QtCore.QRect(180, 30, 16, 16))
        self.comms_onoff.setStyleSheet("QLabel{background-color: red;}")
        self.comms_onoff.setText("")
        self.comms_onoff.setObjectName("comms_onoff")
        self.comms_label = MyLabel(self.widget)
        self.comms_label.setGeometry(QtCore.QRect(80, 30, 61, 20))
        self.comms_label.setObjectName("comms_label")
        self.laser_label = MyLabel(self.widget)
        self.laser_label.setGeometry(QtCore.QRect(80, 70, 61, 20))
        self.laser_label.setObjectName("laser_label")
        self.laser_onoff = MyIndicator(self.widget)
        self.laser_onoff.setGeometry(QtCore.QRect(180, 70, 16, 16))
        self.laser_onoff.setStyleSheet("QLabel{background-color: red;}")
        self.laser_onoff.setText("")
        self.laser_onoff.setObjectName("laser_onoff")
        self.pushButton = MyPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 50, 126, 32))
        self.pushButton.setObjectName("pushButton")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 140, 84, 22))
        self.horizontalSlider.setToolTip("")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        LaserController.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LaserController)
        self.statusbar.setObjectName("statusbar")
        LaserController.setStatusBar(self.statusbar)

        self.retranslateUi(LaserController)
        QtCore.QMetaObject.connectSlotsByName(LaserController)

    def retranslateUi(self, LaserController):
        _translate = QtCore.QCoreApplication.translate
        self.indicators.setText(_translate("LaserController", "Status indicators"))
        self.wavelength_label.setText(_translate("LaserController", "Wavelength (nm)"))
        self.int_display_2.setText(_translate("LaserController", "Intensity (W)"))
        self.cur_label.setText(_translate("LaserController", "Current (A)"))
        self.comms_label.setText(_translate("LaserController", "Comms:"))
        self.laser_label.setText(_translate("LaserController", "Laser:"))
        self.pushButton.setText(_translate("LaserController", "Laser ON/OFF"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LaserController = QtWidgets.QMainWindow()
    ui = Ui_LaserController()
    ui.setupUi(LaserController)
    LaserController.show()
    sys.exit(app.exec_())
